name: Python Unit Tests
on:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  build:
    name: Run Python Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r utils/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pip install pytest-cov
        pip install uuid
        pytest utils/tests --doctest-modules --junitxml=junit/test-results.xml --cov=utils/functions --cov-report=xml:junit/coverage.xml
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      if: success() || failure()
      with:
        pytest-xml-coverage-path: junit/coverage.xml
        unique-id-for-comment: ${{ matrix.python-version }}
        title: Test Coverage Report - Python ${{ matrix.python-version }}
        badge-title: Test Coverage
        hide-badge: false
        hide-report: false
        create-new-comment: false
        hide-comment: false
        report-only-changed-files: false
        remove-link-from-badge: false
        junitxml-path: junit/test-results.xml
        junitxml-title: Python ${{ matrix.python-version }} Test Results
